### ISSUE TITLE
DSit anti surf preventing physgun to non admins

### ISSUE THREAD

**Issue by Extra-Mental** [roboderpy/dbot_projects#1]
The issue occurs when"Anti surf while players are sitting on entities" is on.

If you sit on a prop that's not owned by an admin or of higher power, the owner of the prop is unable to move it.

**Comment by roboderpy** [comment]
Yes, he is unable to physgun as long as he sits on prop. Did you expect anything else from this option?

Also it is better to report issues there https://git.dbot.serealia.ca/dbot/dbot_projects/issues

**Comment by Extra-Mental** [comment]
That's not what I mean, the "owner of the prop" cannot move it. If you run up an sit on someone's base prop, they can't physgun it, causing it to be a minge tool.

**Comment by roboderpy** [comment]
Player A spawns a prop and sits on it. He can not physgun it, but he want to get inside a home on DarkRP server. Player B disables collisions of prop and pushes prop with player inside home. Player A is now inside home.

If you are running sandbox server, just disable this option
