### ISSUE TITLE
[DSit] You can not sit right now

### ISSUE THREAD

**Issue by summersonne** [roboderpy/dbot_projects#2]
Error while pressing ctrl+e

every time

**Comment by roboderpy** [comment]
https://github.com/roboderpy/dbot_projects/blob/master/dsit/lua/autorun/server/sv_dsit.lua#L309-L320

**Comment by roboderpy** [comment]
Check your addons

**Comment by summersonne** [comment]
Addons are no use in this case. Dsit not working in Cinema mode but works in sandbox.

**Comment by roboderpy** [comment]
Problem is on Cinema's side

https://github.com/pixeltailgames/cinema/blob/6732dfdb241fcc220a45f8bcd70eedb4f01ffecc/cinema/gamemode/modules/seats/sv_init.lua#L144-L150

I can't solve that

**Comment by roboderpy** [comment]
But https://github.com/pixeltailgames/cinema/pull/122/files fixed this issue

**Comment by roboderpy** [comment]
I don't know what is wrong with this hook on your side
