### ISSUE TITLE
Causes lua issues when 'str' is nil

### ISSUE THREAD

**Issue by Linus045** [roboderpy/DBot_Projects#3]
https://github.com/roboderpy/dbot_projects/blob/bd32ae32d2a4bf820d911e63fe0684a3c775a05f/ulxpp/lua/autorun/ulxpp/cl_chat.lua#L25

This line causes a lua error when the 'str' parameter is nil.
It happens when i press Tab in the chat to use the standart autocomplete function for names.

**Comment by roboderpy** [comment]
for the love of god, please report issues on my tracker

fixed
